海戦ゲームのメッセージ表示機能追加
konta3291/Battleship pull request #17
Opened 2022-09-20 07:16 UTC by konta3291

#### 海戦ゲームでメッセージを表示する機能を追加しました。
不足しているところ、よりよい方法、よりよい処理の流れがありましたら教えていただきたいです。
お忙しいところ恐れ入りますが、よろしくお願いいたします。

2022-09-20 23:51 UTC, Takatatsu9 reviewed
Done

2022-09-20 23:51 UTC, Takatatsu9 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +                ElseIf "右".Equals(position) Then
[IMO] 全部`position`との比較なんだしSelect Caseでよくない？

2022-09-20 23:51 UTC, Takatatsu9 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                Assert.IsTrue(isResultEqual)
[IMO] boolean変数に判定結果を入れてAssertionするんじゃなくて、判定するところで毎回Assertionすべき。
テストがコケたとき、想定する値はAだったのに実際に返ってきた値はBだった、ってのを出してくれる。

2022-09-20 23:51 UTC, Takatatsu9 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +            For Each position As String In {"上", "下", "左", "右"}
[IMO] こういう何か列挙して処理させたいなら列挙型使ってね

2022-09-21 00:17 UTC, nabemasamasa reviewed
Done

2022-09-21 00:17 UTC, nabemasamasa commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                Assert.IsTrue(isResultEqual)
[imo] TableRowAndColumnNumberのListを↓のような文字列に変換するメソッドを用意してそれでAssertするのはどうだろう？NUnitでテストがコケた時にTrue/Falseだけだとどんな風にコケたのかも情報がないし。
```
r, c
3, 3
5, 3
4, 2
4, 4
```

2022-09-21 00:17 UTC, nabemasamasa commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                    sut.GetSquaresToSearch(rowNumber, columnNumber, tableLength)
[nits] 引数を変数化しておくことで、わかりやすいようにするのは確かに有効な手段ではあるけれど、これなら名前付き引数で十分そう。
`sut.GetSquaresToSearch(row:=4, column:=3, tableLength:=8)`

2022-09-21 00:17 UTC, nabemasamasa commented on Battleship/SquareToSearch/WithinCursorMove.vb
> +    Public Class TableRowAndColumnNumber
[nits] `WithinCursorMove.vb`に一緒にするんじゃなくて、一つのファイルに分けたい……
`TableRowAndColumnNumber`クラスはこのクラスだけの持ち物じゃないし、他でも使い出があるなら同じファイル内に定義しない方が首が回りやすくなるはず。(クラス削除したくなった時とか)
NameSpaceで見てフォルダの直下にいるはずのクラスがいないのも気持ち悪いし。

2022-09-21 00:17 UTC, nabemasamasa commented on Battleship/SquareToSearch/WithinTwoCursorMove.vb
> +                                                       "右斜上", "左斜上", "右斜下", "左斜下"}
[imo] `上上` `下下` `下左`みたいに「上下左右」の繰り返しで書く方が、「２つ上」とか「右斜め上」で書くよりもスッキリできそう。
具体的には、positionに対してさらにForEachを回して`上`cならRowを引く、`下`cならRowを足す、`左`cならColumnを引く、、、、で`上上`なら{`上`, `上`}でRowを計2回引くし、
`上右`なら{`上`, `右`} だから`{RowNumberを1回引く, ColumnNumberを1回足す}`となる。

2022-09-21 00:17 UTC, nabemasamasa commented on Battleship.Test/SquareToSearch/WithinTwoCursorMoveTest.vb
> +                        isResultEqual = False
よく考えたら、Booleanに突っ込むんじゃなくてForの中で一回一回Assertしても良いのでは？
コケた時点でAssertFailedExceptionの例外が起こってテストがコケるわけだし。
(文字列でAssertする方がコケた時全体が見れてより良いと思ってるけど、こういう解法もあるよという事で`imo`も`nits`も何もつけずコメントだけの「感想」)
```
For Each .....
  Assert.That(result.Row, is.EqualTo(rowsExpected(i))))
  Assert.That(result.Column, is.EqualTo(columnsExpected(i))))
Next
```

2022-09-21 00:17 UTC, nabemasamasa commented on Battleship/DistanceToEnemyship.vb
> +    Public Function IsEnemyWithinOneCursorMove(table As Integer()(), rowNumber As Integer, columnNumber As Integer) As Boolean
[imo] 私なら`Is`じゃなくて「存在する」の`Exists`でより意味を明確にする

2022-09-21 00:17 UTC, nabemasamasa commented on Battleship.Test/Message/AttackedMessageTest.vb
> +            <TestCase(4, 3)>'敵船の下のマス
コメントわかりやすい 👍

2022-09-21 00:17 UTC, nabemasamasa commented on Battleship.Test/Message/AttackedMessageTest.vb
> +                Assert.That(result, [Is].EqualTo("敵船は近くにいないです"))
ちなみに、Assert.Thatの第三引数は`message`で、テストがコケた際に参考情報としてメッセージ表示してくれたはず。
[nits] 第三引数に参考情報として`敵船の２つ上のマス`とか設定するのはどう？

2022-09-21 00:17 UTC, nabemasamasa commented on Battleship.Test/Message/AttackedMessageTest.vb
> +            sut = New Battleship.Message.AttackedMessage
[nits] `Import`を使えば、毎回`AttackedMessage`をNameSpaceフルで書かなくて良さそう。(既存の名前と被ってたりしてダメだったかな？)

2022-09-21 00:17 UTC, nabemasamasa commented on Battleship.Test/Message/AttackedMessageTest.vb
> +        New Integer() {0, 0, 0, BattleshipGame.TypeOfSquare.Enemy, 0, 0, 0, 0},
[imo] `DistanceToEnemyship`の機能に依存してるから、毎回ちゃんとTableを用意して、敵船を用意して、その近くの座標でテストを書く必要がある。
依存性注入(Dependency Injection)して偽装すれば、Tableを用意しなくても簡単にテストが書けるし、`DistanceToEnemyship`の影響を受けずらい

2022-09-21 01:59 UTC, konta3291 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +            For Each position As String In {"上", "下", "左", "右"}
ご指摘ありがとうございます。
かしこまりました、列挙型を追加します。

2022-09-21 01:59 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                Assert.IsTrue(isResultEqual)
ご指摘ありがとうございます。
テストがコケた際にどの値でコケたのかわかるように修正します。

2022-09-21 02:00 UTC, konta3291 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +                ElseIf "右".Equals(position) Then
ご指摘ありがとうございます。
すべてposition比較なためSelect Caseでもよろしいと思うのですが、以前 @danielkaneko さんから頂いた指摘の中でSelet Caseを使っていたところの修正を行っているため、こちらでもSelect Caseは使わないほうがよろしいかと思いIF文で書きました。

以前修正した個所では、Select Caseで聞いていたものはメソッドの中のメインの処理ではなかったためFactoryメソッドを作り、Select Caseで聞いていた処理を別のところに移しました。

今回はIF文で聞いている処理がメソッドのメイン処理であるためFactoryメソッドを作る必要がなく、そのためSelect Caseを使ってもよろしいと思うのですが、この考え方は間違いでしょうか。


お忙しいところ恐れ入りますが、お時間があるとき教えていただきたいです。
長くなってしまい申し訳ありません。

2022-09-21 02:04 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                    sut.GetSquaresToSearch(rowNumber, columnNumber, tableLength)
ご指摘ありがとうございます。
かしこまりました、名前付き引数に変更します。

2022-09-21 02:06 UTC, konta3291 commented on Battleship/SquareToSearch/WithinCursorMove.vb
> +    Public Class TableRowAndColumnNumber
ご指摘ありがとうございます。
かしこまりました、別のファイルに移します。

2022-09-21 02:11 UTC, konta3291 commented on Battleship/SquareToSearch/WithinTwoCursorMove.vb
> +                                                       "右斜上", "左斜上", "右斜下", "左斜下"}
ご指摘ありがとうございます。
かしこまりました、いただいた指摘をもとに処理を変更します。

2022-09-21 02:18 UTC, konta3291 commented on Battleship/DistanceToEnemyship.vb
> +    Public Function IsEnemyWithinOneCursorMove(table As Integer()(), rowNumber As Integer, columnNumber As Integer) As Boolean
ご指摘ありがとうございます。
より意味が明確なExistsに変更します。

2022-09-21 02:19 UTC, konta3291 commented on Battleship.Test/Message/AttackedMessageTest.vb
> +            <TestCase(4, 3)>'敵船の下のマス
ありがとうございます。

2022-09-21 02:20 UTC, konta3291 commented on Battleship.Test/Message/AttackedMessageTest.vb
> +                Assert.That(result, [Is].EqualTo("敵船は近くにいないです"))
ご指摘ありがとうございます。
かしこまりました、どこでコケたのかわかりやすくするために第三引数のmessageを追加します。

2022-09-21 02:22 UTC, konta3291 commented on Battleship.Test/Message/AttackedMessageTest.vb
> +            sut = New Battleship.Message.AttackedMessage
ご指摘ありがとうございます。
かしこまりました、Importします。

2022-09-21 02:23 UTC, konta3291 commented on Battleship.Test/Message/AttackedMessageTest.vb
> +        New Integer() {0, 0, 0, BattleshipGame.TypeOfSquare.Enemy, 0, 0, 0, 0},
ご指摘ありがとうございます。
依存性注入(Dependency Injection)について調べ、追加します。

2022-09-21 02:37 UTC, nabemasamasa commented on Battleship.Test/Message/AttackedMessageTest.vb
> +        New Integer() {0, 0, 0, BattleshipGame.TypeOfSquare.Enemy, 0, 0, 0, 0},
もし調べてみて修正できそうなら、事前に理解を確認したいです。
詰まったりしたら聞いてみてください。
ただ、今日(9/21)は13:30～15:00まで打ち合わせなので、それ以降で……。

2022-09-21 02:43 UTC, konta3291 commented on Battleship.Test/Message/AttackedMessageTest.vb
> +        New Integer() {0, 0, 0, BattleshipGame.TypeOfSquare.Enemy, 0, 0, 0, 0},
かしこまりました、調べ終わり次第報告させていただきます。

2022-09-21 02:45 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                Assert.IsTrue(isResultEqual)
ご指摘ありがとうございます。
 @nabemasamasa さんからコメントとして頂いた下記の方法でどんな風にコケたのかわかるようにしようと思うのですが、やはり文字列に変換するメソッドを作るやり方の方が好ましいでしょうか。
> Assert.That(result.Row, is.EqualTo(rowsExpected(i))))
  Assert.That(result.Column, is.EqualTo(columnsExpected(i))))

2022-09-21 02:47 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinTwoCursorMoveTest.vb
> +                        isResultEqual = False
ご意見いただきありがとうございます。

2022-09-21 03:09 UTC, nabemasamasa commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                Assert.IsTrue(isResultEqual)
文字列だとコケた時の全貌が見えやすいです。
ForEachの中のAssertだと1列、1行単位での比較だからその一点がコケてる事しかわかりません。
4,4に対する周囲マスを検証するとして
例えば、行列{{4,3},{4,5},{3,4},{5,4}}のはずが{{4,3},{4,5},{4,4},{5,4}}とかになっちゃってたとしたら、
一個目のAssertで行を見て、下みたいになるから、情報量が少ない(エラー行で行か列かはわかるけど、、、)
```
Was 4
Expected 3
'スタックトレースでAssert.That(actual.Row, Is.EqualTo(expected.Row))の行数を示すから行だという事はわかる
```

全体で比較するなら例えば下のような感じになって、ピンポイントで「上」が間違ってそうって気づきやすい、、、くらいかな。
```
Was 
r,c
4,3
4,5
3,4
5,4
Expectd 
4,3
4,5
4,4
5,4
```

2022-09-21 04:11 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                Assert.IsTrue(isResultEqual)
申し訳ありません。
どう実装すればよろしいのかわからないため、本日の @nabemasamasa さんの打ち合わせ終了後に教えていただくことは可能でしょうか。

2022-09-21 04:17 UTC, nabemasamasa commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                Assert.IsTrue(isResultEqual)
引数がCellRowAndCol?のListの戻り値String型のFunctionで、結果用のString変数に対してForEachでぐるぐるRow, Columnと改行を追加して返すだけでいいと思ってました。

2022-09-21 04:26 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                Assert.IsTrue(isResultEqual)
ご説明いただきありがとうございます。
かしこまりました。メソッドを作りどのようにテストミスしたのかわかりやすいように処理を変更します。

2022-09-21 04:31 UTC, Takatatsu9 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +                ElseIf "右".Equals(position) Then
Select Caseは使ってはいけない禁忌の構文じゃないので普通に使っていいです。
前言いましたっけ？Select Case内に更にSelect Caseがあるなら再考を要するけどそうじゃないならいいって。

2022-09-21 04:36 UTC, Takatatsu9 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                Assert.IsTrue(isResultEqual)
@nabemasamasa ちなみにFhi.Fw入れてるのでDebugStringMaker使えますよ。
Fhi.Fw.Testの参照はしてないので設定しなきゃですけど。

2022-09-21 04:44 UTC, konta3291 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +                ElseIf "右".Equals(position) Then
ご回答ありがとうございます。
以前も言っていただいております。もう一度聞いてしまい申し訳ありません。

かしこまりました。すべてpositionとの比較なためselect Caseに変更します。
ありがとうございます。

2022-09-21 05:03 UTC, danielkaneko reviewed
Done( 9af18ea )まで

2022-09-21 07:52 UTC, nabemasamasa commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                Assert.IsTrue(isResultEqual)
あ、そっか。入ってるのか。
問題は「教育」が終わった後、他の現場に行ったらDebugStringMakerもどきを作らないといけない事かな……。
とは言え、それは別のお話か。

@konta3291  DebugStringMakerTest見て真似できそうだったら、そっちを使ってもいいです！

2022-09-21 07:54 UTC, nabemasamasa commented on Battleship.Test/Message/AttackedMessageTest.vb
> +        New Integer() {0, 0, 0, BattleshipGame.TypeOfSquare.Enemy, 0, 0, 0, 0},
Interface作って、初期動作とテスト用の動作を切り替える実装を伝授しました。
(我々がいつもやってるようなやり方。
IBehavior作って、コンストラクタ引数でbehaviorの実装(Implementsクラス)受け取ったらその実装で動かす、そうじゃなければDefaultBehaviorの実装で動かす)

2022-09-21 23:10 UTC, konta3291 commented on Battleship.Test/Message/AttackedMessageTest.vb
> +        New Integer() {0, 0, 0, BattleshipGame.TypeOfSquare.Enemy, 0, 0, 0, 0},
教えていただきありがとうございます。

2022-09-21 23:13 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                Assert.IsTrue(isResultEqual)
かしこまりました。

2022-09-22 05:02 UTC, danielkaneko reviewed
Done

2022-09-23 02:06 UTC, konta3291 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +                ElseIf "右".Equals(position) Then
SelectCaseに修正しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/bd67e9a64285115f098d18cf283d9f541546fa6f
ご確認よろしくお願いします。

2022-09-23 02:07 UTC, konta3291 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +            For Each position As String In {"上", "下", "左", "右"}
列挙型に変更しました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/5ec9bda4313381e5a86406b6f651ca6a443fb7a5

2022-09-23 02:08 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                Assert.IsTrue(isResultEqual)
どこでテストが失敗したかわかりやすいように修正しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/f3e91071f66c9a37c4842ed595475cc09b4f46fc
ご確認よろしくお願いします。

2022-09-23 02:09 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                Assert.IsTrue(isResultEqual)
どこでテストが失敗したかわかりやすいように修正しました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/f3e91071f66c9a37c4842ed595475cc09b4f46fc

2022-09-23 02:10 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                    sut.GetSquaresToSearch(rowNumber, columnNumber, tableLength)
名前付け引数に変更しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/91fccfbec32bb7c370102ba82dfad6342d89b807
ご確認よろしくお願いします。

2022-09-23 02:10 UTC, konta3291 commented on Battleship/SquareToSearch/WithinCursorMove.vb
> +    Public Class TableRowAndColumnNumber
別のファイルに移しました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/4831a9250952b5f6a43d8d605ae9eb62f6b608ba

2022-09-23 02:11 UTC, konta3291 commented on Battleship/DistanceToEnemyship.vb
> +    Public Function IsEnemyWithinOneCursorMove(table As Integer()(), rowNumber As Integer, columnNumber As Integer) As Boolean
メソッド名を変更しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/8f3e955ec72601ea10809bc6a8e8609c6b94c159
ご確認よろしくお願いします。

2022-09-23 02:12 UTC, konta3291 commented on Battleship.Test/Message/AttackedMessageTest.vb
> +                Assert.That(result, [Is].EqualTo("敵船は近くにいないです"))
メッセージを追加しました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/032515757738d0bebcdce9cadf3dd2019b0f75dc

2022-09-23 02:12 UTC, konta3291 commented on Battleship.Test/Message/AttackedMessageTest.vb
> +            sut = New Battleship.Message.AttackedMessage
Importを追加しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/2f86b4a98b58e223becdbf3d1d6a3793fc4824e0
ご確認よろしくお願いします。

2022-09-23 02:13 UTC, konta3291 commented on Battleship.Test/Message/AttackedMessageTest.vb
> +        New Integer() {0, 0, 0, BattleshipGame.TypeOfSquare.Enemy, 0, 0, 0, 0},
依存性注入パターンを追加しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/d0549cd86a91b3b874a2f38dfba779d169f687e9
ご確認よろしくお願いします。

2022-09-23 02:20 UTC, Takatatsu9 requested changes
Done

2022-09-23 02:20 UTC, Takatatsu9 commented on Battleship/TableRowAndColumnNumber.vb
> +Public Class TableRowAndColumnNumber
[nits] クラス名長すぎる。「テーブル」「座標」の2単語で表現できる

2022-09-23 02:20 UTC, Takatatsu9 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +            上
[MUST] 名称に日本語禁止です

2022-09-23 02:20 UTC, Takatatsu9 commented on Battleship/SquareToSearch/WithinTwoCursorMove.vb
> +            二つ上
[MUST] こっちも

2022-09-23 02:20 UTC, Takatatsu9 commented on Battleship/Message/AttackedMessage.vb
> +            ''' <returns>攻撃済みならTrue、そうでなければFalse</returns>
[MUST] コメントはInterface側に書いてください

2022-09-23 02:20 UTC, Takatatsu9 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +            End Function
[nits] このメソッドは一番上にあるといいかな。下だと場所的にわかりづらい。

2022-09-23 02:37 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +            End Function
ご指摘ありがとうございます。
わかりやすいように一番上に移動させます。

2022-09-23 02:37 UTC, konta3291 commented on Battleship/Message/AttackedMessage.vb
> +            ''' <returns>攻撃済みならTrue、そうでなければFalse</returns>
ご指摘ありがとうございます。
Interface側にコメントを修正します。

2022-09-23 02:37 UTC, konta3291 commented on Battleship/SquareToSearch/WithinTwoCursorMove.vb
> +            二つ上
ご指摘ありがとうございます。
こちらも名称を変更します。

2022-09-23 02:37 UTC, konta3291 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +            上
ご指摘ありがとうございます。
名称を変更します。

2022-09-23 02:37 UTC, konta3291 commented on Battleship/TableRowAndColumnNumber.vb
> +Public Class TableRowAndColumnNumber
ご指摘ありがとうございます。
クラス名が長いため名前を変更します。

2022-09-23 02:53 UTC, nabemasamasa reviewed
Done

2022-09-23 02:53 UTC, nabemasamasa commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                    returnString = returnString & position.RowNumber & "," & position.ColumnNumber & vbCrLf
[imo] `returnString  &= $"{positon.Row},{Position.Column}{vbcrlf}"`とかで書けそう
連結演算子と、文字列補間。

2022-09-23 02:53 UTC, nabemasamasa commented on Battleship.Test/SearchForEnemyshipTest.vb
> -        <TestCase(4, 3, "敵船の下のマス")>
> メソッド結果に依存していたメソッドを修正

👍 👍 👍

2022-09-23 02:59 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                    returnString = returnString & position.RowNumber & "," & position.ColumnNumber & vbCrLf
ご指摘ありがとうございます。
連結演算子と文字列補間式を使い修正します。

2022-09-23 02:59 UTC, konta3291 commented on Battleship.Test/SearchForEnemyshipTest.vb
> -        <TestCase(4, 3, "敵船の下のマス")>
ありがとうございます。

2022-09-23 05:07 UTC, konta3291 commented on Battleship/Message/AttackedMessage.vb
> +            ''' <returns>攻撃済みならTrue、そうでなければFalse</returns>
MustOverrideとOverridesを使っているのですが、こちらのコメントもOverridesは不要でしょうか。

2022-09-23 05:07 UTC, danielkaneko commented
Done

2022-09-23 05:10 UTC, Takatatsu9 commented on Battleship/Message/AttackedMessage.vb
> +            ''' <returns>攻撃済みならTrue、そうでなければFalse</returns>
Overridesしたメソッドにマウスカーソル合わせてMustOverrideに書いたコメントが出てきたら不要です

2022-09-23 05:13 UTC, konta3291 commented on Battleship/Message/AttackedMessage.vb
> +            ''' <returns>攻撃済みならTrue、そうでなければFalse</returns>
かしこまりました。
ありがとうございます。

2022-09-23 05:20 UTC, konta3291 commented on Battleship/TableRowAndColumnNumber.vb
> +Public Class TableRowAndColumnNumber
クラス名を変更しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/66e8f76005528617f454d6f43c126ab30cd11e07
ご確認よろしくお願いします。

2022-09-23 05:21 UTC, konta3291 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +            上
列挙値を修正しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/9117f707aad671af43a82e703261acfd51d8ff37
ご確認よろしくお願いします。

2022-09-23 05:21 UTC, konta3291 commented on Battleship/SquareToSearch/WithinTwoCursorMove.vb
> +            二つ上
こちらの列挙値も修正しました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/9117f707aad671af43a82e703261acfd51d8ff37

2022-09-23 05:23 UTC, konta3291 commented on Battleship/Message/AttackedMessage.vb
> +            ''' <returns>攻撃済みならTrue、そうでなければFalse</returns>
Interface側にコメントを書きました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/d9c658a97c5aa824cb469e5ea12f9b334f4f9f43

2022-09-23 05:23 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +            End Function
場所を移動させました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/fee17222a3c3b46cf0ce275c889b6d365410f9dd
ご確認よろしくお願いします。

2022-09-23 05:24 UTC, konta3291 commented on Battleship.Test/SquareToSearch/WithinOneCursorMoveTest.vb
> +                    returnString = returnString & position.RowNumber & "," & position.ColumnNumber & vbCrLf
連結演算子と文字列補間式を使い修正しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/d785fb62763ead5476aac78df6d31bc7a9d6e156
ご確認よろしくお願いします。

2022-09-23 07:38 UTC, Takatatsu9 reviewed
Done

2022-09-23 07:38 UTC, Takatatsu9 approved these changes

2022-09-23 07:40 UTC, Takatatsu9 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +                    Case PositionToSearch.Up.ToString
あれ、書いたつもりのコメントが無かった

[nits] Totringやだなぁ。31行目の`[Enum].GetNames(GetType(PositionToSearch))`が諸悪の根源

2022-09-23 07:53 UTC, konta3291 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +                    Case PositionToSearch.Up.ToString
ご指摘ありがとうございます。
[Enum].GetNames(GetType(PositionToSearch))を使わない方法で、ToStringを使わないように修正します。

2022-09-23 08:01 UTC, konta3291 commented on Battleship/SquareToSearch/WithinOneCursorMove.vb
> +                    Case PositionToSearch.Up.ToString
ToStringを使わないように修正しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/41ee7943522f42c65627f9784fc88ed00042663a
ご確認よろしくお願いします。

2022-09-23 08:17 UTC, nabemasamasa reviewed
Done

2022-09-26 04:35 UTC, danielkaneko reviewed
Done

2022-09-26 04:38 UTC, Takatatsu9 reviewed
Done

2022-09-26 05:26 UTC, konta3291 commented
必要の無いことをしていたため修正し[Force-Push](https://github.com/konta3291/Battleship/compare/e3fef8ea70bfa3570886c9f1b194d52500d521b5..b44fa96ee78bce81eab0024d0b3596c996be0f25)しました。

2022-09-26 05:30 UTC, konta3291 commented on Battleship/SquareToSearch/WithinTwoCursorMove.vb
> +                                                       "右斜上", "左斜上", "右斜下", "左斜下"}
いただいた指摘をもとに処理を変更しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/b44fa96ee78bce81eab0024d0b3596c996be0f25
ご確認よろしくお願いします。

2022-09-26 23:18 UTC, nabemasamasa reviewed
Done 👍

2022-09-26 23:18 UTC, nabemasamasa commented on Battleship/Message/AttackedMessage.vb
> +                    {Position.Right, Position.Naught}}
[nits] `Naught`なしでも動きそう。パッと見、二次元配列でさえあれば、二列目が何個の配列でもいいようなロジックになってそう。

2022-09-26 23:24 UTC, konta3291 commented on Battleship/Message/AttackedMessage.vb
> +                    {Position.Right, Position.Naught}}
ご指摘ありがとうございます。
二列目の個数を2個に制限したいのですが、調べても見つからないです。
個数制限することは可能でしょうか。

2022-09-26 23:33 UTC, nabemasamasa commented on Battleship/Message/AttackedMessage.vb
> +                    {Position.Right, Position.Naught}}
？？？
とりあえず、型で配列の長さを制限するのはたぶん出来ないです。
ロジックで、指定した長さ以外だったら例外になるようにしておくぐらいしかないです。

個人的には、むしろ探索範囲が何マスでもいいよで可変でいいとは思いましたが……。
以下のような配列でも「動きそう」の`[nits]`です。
`{{Position.Up},{Position.Down},{Position.Left},{Position.Right}}`

2022-09-26 23:48 UTC, konta3291 commented on Battleship/Message/AttackedMessage.vb
> +                    {Position.Right, Position.Naught}}
可変ではいけないと思っておりました。
かしこまりました、いただいた [nits] 指摘を修正します。

2022-09-26 23:55 UTC, konta3291 commented on Battleship/Message/AttackedMessage.vb
> +                    {Position.Right, Position.Naught}}
空位置を設定する必要がなかったため削除しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/7d4fa4ad8cf783bd61423e9044a36524ef8089db
ご確認よろしくお願いします。

2022-09-27 00:00 UTC, nabemasamasa reviewed
Done

2022-09-27 00:00 UTC, nabemasamasa approved these changes

2022-09-27 01:53 UTC, danielkaneko reviewed
Done

2022-09-27 01:53 UTC, danielkaneko commented on Battleship/Message/AttackedMessage.vb
>              Public Function IsHitAnEnemyship(table As Integer()(), rowNumber As Integer, columnNumber As Integer) _
[imo]コメント忘れですかね？

2022-09-27 02:03 UTC, konta3291 commented on Battleship/Message/AttackedMessage.vb
>              Public Function IsHitAnEnemyship(table As Integer()(), rowNumber As Integer, columnNumber As Integer) _
ご指摘ありがとうございます。
コメントはInterface側に書いており、Implements側のメソッドにカーソルを当てた際にコメントが表示されるため不要だと考え書いておりませんでした。

2022-09-27 02:08 UTC, danielkaneko commented on Battleship/Message/AttackedMessage.vb
>              Public Function IsHitAnEnemyship(table As Integer()(), rowNumber As Integer, columnNumber As Integer) _
なるほど。なら、大丈夫そうですね

2022-09-27 06:21 UTC, nabemasamasa reviewed
Done 👍

2022-09-30 05:01 UTC, Takatatsu9 reviewed
Done

2022-09-30 05:01 UTC, Takatatsu9 commented on Battleship/SquareToSearch.vb
> +Public Class SquareToSearch
「正方形で検索」ってなんかよくわからん・・・。「周囲を検索」じゃダメ？

2022-09-30 05:17 UTC, konta3291 commented on Battleship/SquareToSearch.vb
> +Public Class SquareToSearch
コメントありがとうございます。
ここでは敵船がいるか調べる対象マスを返しています。
検索はしていないため「周囲を検索」という名前は合わないかと思います。

2022-09-30 05:20 UTC, Takatatsu9 commented on Battleship/SquareToSearch.vb
> +Public Class SquareToSearch
検索していないという主張は「Search」という単語を使わないよう修正するという意味で捉えていいですか？

2022-09-30 05:25 UTC, konta3291 commented on Battleship/SquareToSearch.vb
> +Public Class SquareToSearch
検索するためのマスという意味になるように、Square to Searchと命名しました。
検索は中では行っていなく、わかりづらいためクラス名を変更します。

2022-09-30 06:34 UTC, konta3291 commented on Battleship/SquareToSearch.vb
> +Public Class SquareToSearch
クラス名とそれに伴いメソッド名も変更しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/5a5af1ed19cb822f5a6cd1dec53c2fba8a5e84b7
ご確認よろしくお願いします。

2022-10-03 04:28 UTC, danielkaneko reviewed
Done

2022-10-04 00:29 UTC, nabemasamasa submitted a review, later dismissed
~コーディングルール違反が混ざってしまった~ 直後に直ってた

2022-10-04 00:29 UTC, nabemasamasa commented on Battleship/Message/AttackedMessage.vb
> +            Private ReadOnly SquareAround As New SquareAround
あ、大文字化してしまった
[VB.NET.コーディングルール.md#29-private--protected--friend--protected-friendスコープのインスタンス変数](http://auto3tsv132/daniel-soft/knowledge/blob/master/VB.NET.%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%AB.md#29-private--protected--friend--protected-friend%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9%E5%A4%89%E6%95%B0)

2022-10-04 00:29 UTC, nabemasamasa commented on Battleship/SquareAround.vb
> +    Public Function ConvertPositionToSquares(rowNumber As Integer, columnNumber As Integer, positions As Position(,),
[Q] ふっと思ったんだけど、これSquaresじゃなくてCoordinatesじゃない？
領域たちじゃなくて座標たちな気がする。

2022-10-04 00:29 UTC, nabemasamasa commented on Battleship/SquareAround.vb
> +    Public Function ConvertPositionToCoordinate(rowNumber As Integer, columnNumber As Integer,
[imo] VB.NETなら、同名メソッド(同じ役割)で引数違いのOverloadsが使える。
やらせたい責務が同じであるならば、Overloadsの実装でもいいと思う。

2022-10-04 00:43 UTC, konta3291 commented on Battleship/Message/AttackedMessage.vb
> +            Private ReadOnly SquareAround As New SquareAround
ご指摘ありがとうございます。
[こちらのコミット](https://github.com/konta3291/Battleship/pull/17/commits/8037d17a9f9aa02ccad500d2e31d58bf1ee22a3d)では

2022-10-04 00:45 UTC, konta3291 commented on Battleship/Message/AttackedMessage.vb
> +            Private ReadOnly SquareAround As New SquareAround
ご指摘ありがとうございます。
大文字にしてしまい申し訳ありません。
こちらのコミット：https://github.com/konta3291/Battleship/pull/17/commits/8037d17a9f9aa02ccad500d2e31d58bf1ee22a3d
でクラス名を変更し小文字に修正しております。

2022-10-04 00:52 UTC, konta3291 commented on Battleship/SquareAround.vb
> +    Public Function ConvertPositionToSquares(rowNumber As Integer, columnNumber As Integer, positions As Position(,),
Positionに合った座標を返すメソッドとテーブルからはみ出た座標を修正するメソッドがあり、座標を修正することでテーブルのマスになるという認識でSquaresにしておりました。

2022-10-04 01:11 UTC, konta3291 commented on Battleship/SquareAround.vb
> +    Public Function ConvertPositionToCoordinate(rowNumber As Integer, columnNumber As Integer,
ご指摘ありがとうございます。
無理やり名前を変えていたため、Overloadsの実装を行います。

2022-10-04 01:24 UTC, konta3291 commented on Battleship/SquareAround.vb
> +    Public Function ConvertPositionToCoordinate(rowNumber As Integer, columnNumber As Integer,
メソッド名を修正しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/ce588f44b0a06d9060cb1672de06a1410dcc42d1
ご確認よろしくお願いいたします。

2022-10-04 04:50 UTC, nabemasamasa commented on Battleship/Message/AttackedMessage.vb
> +            Private ReadOnly SquareAround As New SquareAround
レビュー中の間にPushされてた！失礼しました、取り下げます！

2022-10-04 04:56 UTC, nabemasamasa reviewed
Done

2022-10-04 04:58 UTC, nabemasamasa commented on Battleship/SquareAround.vb
> +    Public Function ConvertPositionToSquares(rowNumber As Integer, columnNumber As Integer, positions As Position(,),
経緯、理解しました。

2022-10-04 05:15 UTC, danielkaneko reviewed
Done

2022-10-04 05:30 UTC, konta3291 commented
@nabemasamasa さん @danielkaneko さん 
にレビューをしていただいたところのコミット整理を行い[強制Push](https://github.com/konta3291/Battleship/compare/001e5e74707a19f7fcc5ef14405b9881a19a53ec..ca6806bd245fbd65d08295d775800643a1baaf10) しました。
変更点はないためレビューしていただかなくて大丈夫です。


@Takatatsu9 さん
お忙しいところ恐れ入りますが、お時間があるとき下記のコミットのレビューよろしくお願いいたします。
https://github.com/konta3291/Battleship/pull/17/commits/4d05a4512c6171b57b13bf952046e70ba8d0763c https://github.com/konta3291/Battleship/pull/17/commits/ca6806bd245fbd65d08295d775800643a1baaf10

2022-10-06 01:25 UTC, nabemasamasa commented
@Takatatsu9 レビュー依頼きてます。2コミットだから秒だとは思うけど、リマインドです。

2022-10-06 02:04 UTC, Takatatsu9 reviewed
Done

2022-10-06 02:04 UTC, Takatatsu9 commented on Battleship/SearchForEnemyship.vb
> +    ''' 指定座標に敵船が見つかったか
[Q] コメントが過去形ですが、つまり別のメソッドで処理をしたあと
これを呼ぶことで結果が貰えるというメソッドですか？

2022-10-06 02:17 UTC, konta3291 commented on Battleship/SearchForEnemyship.vb
> +    ''' 指定座標に敵船が見つかったか
ご指摘ありがとうございます。
こちらのメソッドで敵船を探しているためメソッド名を変更します。

2022-10-06 02:21 UTC, Takatatsu9 commented on Battleship/SearchForEnemyship.vb
> +    ''' 指定座標に敵船が見つかったか
言いたいことは伝わったのでまあいいんですけど、質問の形式なのでせめて回答は書きましょうね。

2022-10-06 02:27 UTC, konta3291 commented on Battleship/SearchForEnemyship.vb
> +    ''' 指定座標に敵船が見つかったか
申し訳ありません。
もう必要ないかと思いますが、
[Q]の回答：こちらのメソッドで敵船を探す処理を行っております。



コメントを修正しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/b704764b53adf329b581cafc48c9b68f5e5b14ea
ご確認よろしくお願いします。

2022-10-06 02:30 UTC, Takatatsu9 commented on Battleship/SearchForEnemyship.vb
> +    ''' 指定座標で敵船を見つけたか
これ主観か客観か変わっただけで結局過去形じゃん

2022-10-06 02:34 UTC, Takatatsu9 commented on Battleship/SearchForEnemyship.vb
> +    ''' 指定座標で敵船を見つけたか
ちなみに私なら「～が存在するか」で`Exists～`と書きます。

2022-10-06 02:51 UTC, konta3291 commented on Battleship/SearchForEnemyship.vb
> +    ''' 指定座標で敵船を見つけたか
過去形になってしまっており申し訳ありません。
IsFindEnemyshipでは、過去形のコメントになってしまうため @Takatatsu9 さんの考えをいただきメソッド名にExistsを含ませ名前変更します。

2022-10-06 03:01 UTC, konta3291 commented on Battleship/SearchForEnemyship.vb
> +    ''' 指定座標で敵船を見つけたか
メソッド名、コメントが処理にあっていなかったため名前変更をしました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/17/commits/62954393a957b605553501ac4d9d71f8594ed738

2022-10-06 03:01 UTC, Takatatsu9 commented on Battleship/SearchForEnemyship.vb
> +    ''' 指定座標で敵船を見つけたか
別に`IsFindEnemyship`だからといって過去形のコメントにはなりませんよ、
「指定座標周辺の敵船を探す」ってコメントにすればいいだけなんで。

2022-10-06 04:11 UTC, konta3291 commented on Battleship/SearchForEnemyship.vb
> +    ''' 指定座標で敵船を見つけたか
指摘をいただいて適したコメントを考えていく中でIs Findというメソッド名にも違和感が出てきていたため変更しました。

2022-10-06 04:23 UTC, Takatatsu9 reviewed
Done

2022-10-06 08:53 UTC, nabemasamasa approved these changes
Done

2022-10-07 04:16 UTC, danielkaneko reviewed
Done

2022-10-07 04:46 UTC, konta3291 commented
@Takatatsu9 さん @nabemasamasa さん @danielkaneko さん 
修正コミットを整理しforcePushしました。
[変更点](https://github.com/konta3291/Battleship/compare/62954393a957b605553501ac4d9d71f8594ed738..f9acc3eab3beb1ee2603322364a6a0688b93bc07) はございません。

そのためレビューしていただかなくて大丈夫です。
コミットコメントが不適切な場合は教えていただきたいです。

2022-10-07 05:13 UTC, Takatatsu9 reviewed
Done

2022-10-07 05:21 UTC, danielkaneko commented
[nits]
> 適切な攻撃メッセージを表示するために指定範囲に敵船が存在する返す処理追加

5830639 コミットのコミットコメントの日本語に違和感がある気がします。
「敵船が存在するかを返す」みたいなニュアンスですかね？

2022-10-07 05:48 UTC, konta3291 commented
@danielkaneko さん
コミットコメントへのご指摘ありがとうございます。

適切な攻撃メッセージを表示するために指定範囲に敵船が存在する返す処理追加
から
適切な攻撃メッセージを表示するために指定範囲に敵船が存在するか返す処理追加

でいかがでしょうか。

2022-10-07 05:58 UTC, danielkaneko commented
@konta3291 
> 適切な攻撃メッセージを表示するために指定範囲に敵船が存在するか返す処理追加

問題ないと思います。

2022-10-07 06:04 UTC, konta3291 commented
@danielkaneko さん
ご回答ありがとうございます。
かしこまりました、コミットコメントを修正します。

2022-10-07 06:14 UTC, konta3291 commented
@nabemasamasa さん @Takatatsu9 さん @danielkaneko さん
コミットコメントに脱字があったためコメントを修正しForcePushしました。
ソースコードの変更点はございません。レビューしていただかなくて大丈夫です。

2022-10-07 06:38 UTC, danielkaneko commented
Done

2022-10-07 07:55 UTC, merged