コンソールアプリで遊ぶ海戦ゲームを作りました。
konta3291/Battleship pull request #5
Opened 2022-08-22 01:55 UTC by konta3291

#### コンソールアプリで遊ぶ海戦ゲームを作りました。
前回のプルリクが100を超えたため、新しいプルリクを作りました。
足りないところ、不適切なところ、よりよい方法がありましたら教えて頂きたいです。
よろしくお願いいたします。

2022-08-22 04:59 UTC, danielkaneko reviewed
Done ( 50694fe まで)

2022-08-22 05:13 UTC, Takatatsu9 reviewed
Done

2022-08-22 05:13 UTC, Takatatsu9 commented on Battleship.Test/EnemyshipTest.vb
> +        <Test()> Public Sub 下壁に向け垂直に敵船を作ろうとすると上に向けて作る処理に変更される()
[IMO] これ改めて見ると「上に余裕があればTrue」「上にも余裕がなければFalse」の2種類のテストしたほうがいいですね

2022-08-22 05:13 UTC, Takatatsu9 commented on Battleship/Module1.vb
> +    Private Function AskPlayerWantToPlayAgain() As Boolean
[IMO] コメントが不足してると思う。聞くだけじゃないですよね

2022-08-22 05:13 UTC, Takatatsu9 commented on Battleship/Module1.vb
> +    Private Function AskPlayerWantToPlayAgain() As Boolean
[IMO] これクラス化したほうがいいかな。テストはできないけど

2022-08-22 07:44 UTC, konta3291 commented on Battleship.Test/EnemyshipTest.vb
> +        <Test()> Public Sub 下壁に向け垂直に敵船を作ろうとすると上に向けて作る処理に変更される()
ご指摘ありがとうございます。
かしこまりました、テストを追加します。

2022-08-22 07:44 UTC, konta3291 commented on Battleship/Module1.vb
> +    Private Function AskPlayerWantToPlayAgain() As Boolean
ご指摘ありがとうございます。
かしこまりました、コメントを追加します。

2022-08-22 07:44 UTC, konta3291 commented on Battleship/Module1.vb
> +    Private Function AskPlayerWantToPlayAgain() As Boolean
ご指摘ありがとうございます。
かしこまりました、クラス化します。

2022-08-23 00:36 UTC, nabemasamasa reviewed
Done

2022-08-23 00:36 UTC, nabemasamasa commented on Battleship/BattleshipGame.vb
> +    Public Sub BattleshipGame()
今更ながら、名詞始まり…？

2022-08-23 00:36 UTC, nabemasamasa commented on Battleship/BattleshipGame.vb
> +                Dim rowArrow As String = "→"
[nits] `Const`で良さそう

2022-08-23 00:36 UTC, nabemasamasa commented on Battleship/BattleshipGame.vb
> +    Private ReadOnly TOP_EDGE As Integer = 4
[Q] コミット整理後のはずですが、ここ 36bc5fb5b0d46f5c9603fe7af5d009e6c2a4173b で3から4に修正されてる。
けど、はみ出ないようにする処理は変化してない。
矢印を追加させることで処理が変わるから、初出コミットもこのコミットも整合性は担保されてる認識でOKですか？

2022-08-23 01:27 UTC, konta3291 commented on Battleship/Module1.vb
> +    Private Function AskPlayerWantToPlayAgain() As Boolean
別のクラスを作りました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/a17c79565ab2b9c8d758faa3adf348a572d6b147
ご確認よろしくお願いします。

2022-08-23 01:28 UTC, konta3291 commented on Battleship/Module1.vb
> +    Private Function AskPlayerWantToPlayAgain() As Boolean
コメントを追加しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/92d436ace360cf466af8a6b3d7953f7836487825
ご確認よろしくお願いします。

2022-08-23 01:29 UTC, konta3291 commented on Battleship.Test/EnemyshipTest.vb
> +        <Test()> Public Sub 下壁に向け垂直に敵船を作ろうとすると上に向けて作る処理に変更される()
敵船を作る処理とテストを変更しました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/937eb81e717da1c399b9bed8304502f503c2c908

2022-08-23 01:30 UTC, konta3291 commented on Battleship/BattleshipGame.vb
> +    Public Sub BattleshipGame()
ご指摘ありがとうございます。
申し訳ありません。動詞始まりに変更します。

2022-08-23 01:31 UTC, konta3291 commented on Battleship/BattleshipGame.vb
> +                Dim rowArrow As String = "→"
ご指摘ありがとうございます。
かしこまりました、Constに変更します。

2022-08-23 01:34 UTC, Takatatsu9 reviewed
Done

2022-08-23 01:34 UTC, Takatatsu9 commented on Battleship/QuestionForPlayer.vb
>      ''' もう一度遊ぶか聞きます
> もう一度遊ぶか聞くメソッドのコメントが不足していたためコメントを追加

なるほど、もう一度遊ぶか聞くだけで終わりなのがこのメソッドの機能なんですね。
ユーザーに入力は求めないし、求めた結果を返してくれるわけでもないのですね。

2022-08-23 01:34 UTC, Takatatsu9 commented on Battleship.Test/EnemyshipTest.vb
> -
[Q] テストを消したのはどうしてですか？なんとなく理由は察せるけど

2022-08-23 01:44 UTC, konta3291 commented on Battleship/BattleshipGame.vb
> +    Private ReadOnly TOP_EDGE As Integer = 4
矢印が入ることでテーブルの上端の位置が変わり、TOP_EDGEを3から4に変更しています。
矢印を追加する際に必要な変更だと考えたため、コミット整理後でも残しております。

2022-08-23 01:59 UTC, konta3291 commented on Battleship.Test/EnemyshipTest.vb
> -
修正前の敵船を作る処理では、敵船を作るマスに余裕がなかった場合は下方向に作る敵船を上方向に変更しマスに余裕を持たせるように作る処理を行っていました。
例）
 - 敵船のサイズ5 
 - 下向き垂直
 - 行の開始位置5
 の場合、マスに敵船が収まりません。そのため、行の開始位置を変更せず上向きに作るようにしていました。


 ですが、
  - 敵船のサイズ7
  - 下向き垂直
  - 行の開始位置5
 の場合は、上向きに変更しても収まりません。
 
 敵船のサイズに依存しない敵船を作る処理に変更しました。
 そのため、上向きに船を作ることや、左向きに船を作ることがなくなったため必要の無いテストをなくしました。

2022-08-23 02:07 UTC, konta3291 commented on Battleship/QuestionForPlayer.vb
>      ''' もう一度遊ぶか聞きます
申し訳ありません。
何をしているメソッドなのかわかるようにコメントを追加しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/d4c1ce250a7f3dcb1cc3788994faf842eda7aa97
ご確認よろしくお願いします。

2022-08-23 02:08 UTC, konta3291 commented
コメントが不足していたため、修正し強制Pushしました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/d4c1ce250a7f3dcb1cc3788994faf842eda7aa97

2022-08-23 02:21 UTC, konta3291 commented on Battleship/BattleshipGame.vb
> +    Public Sub BattleshipGame()
名前を変更しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/6ca461ead6ad43515b60e3d3131f7bc5a7e17ed0
ご確認よろしくお願いします。

2022-08-23 02:21 UTC, konta3291 commented on Battleship/BattleshipGame.vb
> +                Dim rowArrow As String = "→"
Constに変更しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/38e04ddb5fb89f1457b71ae6a381ac654474695b
ご確認よろしくお願いします。

2022-08-23 04:55 UTC, danielkaneko reviewed
Done ( 52b9751 まで)

2022-08-23 05:06 UTC, Takatatsu9 reviewed
Done

2022-08-23 05:06 UTC, Takatatsu9 commented on Battleship/QuestionForPlayer.vb
> +    ''' Nキーが押されるとFalseを返す
[IMO] 詳細は`returns`に書いてあるから、ここは入力の結果を返すことだけ書けばいいです。
あと改行してもIntelliSenseには繋がって表示されませんか？

2022-08-23 05:06 UTC, Takatatsu9 commented on Battleship/BattleshipGame.vb
> +    Public Sub PlayBattleshipGame()
[nits] Play・・・うーん、コーディングだと「（メディアの）再生」って意味になるかなあ。
コードの命名は動きを書くものだと思ってるので、「遊ぶ」って意味だとすると、
遊ぶのはexeを実行した人間であって、このプログラムに「遊べ」って言ってるわけじゃないしなあ、と。

2022-08-23 05:10 UTC, Takatatsu9 commented on Battleship.Test/EnemyshipTest.vb
> -
[Q] 敵船のサイズに依存しない処理に変えると、どうして上向きや左向きに生成する処理が不要になるんですか？

多分、最後の「そのため」を「その際」に変えただけで説明がつく話かもしれませんけど

2022-08-23 23:17 UTC, konta3291 commented on Battleship.Test/EnemyshipTest.vb
> -
下向きや右向きに敵船を作る際、マスに余裕がない可能性がある場合のみ上向きや左向きに敵船を作る処理を行っていました。
敵船のサイズに依存しない処理に変えることにより、マスに余裕がないことがなくなったため上向きや左向きに生成する処理が不要になりました。

2022-08-23 23:19 UTC, konta3291 commented on Battleship/QuestionForPlayer.vb
> +    ''' Nキーが押されるとFalseを返す
ご指摘ありがとうございます。
改行しても、IntelliSenseでは繋がって表示されていました。
かしこまりました、修正します。

2022-08-23 23:20 UTC, konta3291 commented on Battleship/BattleshipGame.vb
> +    Public Sub PlayBattleshipGame()
ご指摘ありがとうございます。
メソッド名を適した名前に変更します。

2022-08-23 23:22 UTC, Takatatsu9 commented on Battleship.Test/EnemyshipTest.vb
> -
ん？例えば下端から2番目の行に既に敵船が横向きにあったとして、
下端から1番目の部分に敵船を縦方向に生成しようとしても
マスに余裕が無いことはありえないってことですか？

2022-08-24 00:05 UTC, konta3291 commented on Battleship.Test/EnemyshipTest.vb
> -
マスに余裕がない場合や敵船が既にある場合は、正常に敵船を配置できるまで行と列の開始位置と縦横を決める数字を求め続けます。そのため、マスに余裕がなくても大丈夫です。

2022-08-24 00:12 UTC, konta3291 commented on Battleship/QuestionForPlayer.vb
> +    ''' Nキーが押されるとFalseを返す
コメントを修正しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/46209b2a0e16084d1b7e5b20d3631497cd063084
ご確認よろしくお願いします。

2022-08-24 00:15 UTC, konta3291 commented
こちらのコメントが適していなかったため修正しました。https://github.com/konta3291/Battleship/pull/5/commits/46209b2a0e16084d1b7e5b20d3631497cd063084

2022-08-24 00:51 UTC, konta3291 commented
メソッド名をPlayから変更するために強制Pushしました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/2cf10752ed75f33107bb4e78a9cc98b4c1e1954d

2022-08-24 00:52 UTC, konta3291 commented on Battleship/BattleshipGame.vb
> +    Public Sub PlayBattleshipGame()
メソッド名を修正しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/2cf10752ed75f33107bb4e78a9cc98b4c1e1954d
ご確認よろしくお願いします。

2022-08-24 02:30 UTC, Takatatsu9 commented on Battleship.Test/EnemyshipTest.vb
> -
求め続けるというのはどういうことですか？
引数で指定した値を無視して設置できる場所を探すということですか？

2022-08-24 04:11 UTC, nabemasamasa commented on Battleship/BattleshipGame.vb
> +    Private ReadOnly TOP_EDGE As Integer = 4
なるほど、理解しました。ありがとうございます。

2022-08-24 04:27 UTC, konta3291 commented on Battleship.Test/EnemyshipTest.vb
> -
1. 引数で指定した値では敵船を配置できないと判断し、Falseを返します。
 2. Falseを受け取ったメソッドが新しい行と列の開始位置と縦横を決める値を敵船を配置できるか判断するメソッドに渡します。
 3. 敵船が正常に設置できる引数ならTrueを返します。できない場合はFalseを返し1に戻ります。

2022-08-24 05:00 UTC, danielkaneko reviewed
Done ( 36bc5fb まで)

2022-08-24 05:18 UTC, Takatatsu9 commented on Battleship.Test/EnemyshipTest.vb
> -
[Q] 下向き、右向きに生成ができなければ逆向き生成するのを諦めてやり直させるってことですか？

2022-08-24 07:24 UTC, konta3291 commented on Battleship.Test/EnemyshipTest.vb
> -
はい、右向き下向きに生成できなければ逆向きに生成するのではなく、新しい引数を求め下向き右向きで生成できるまで繰り返します。

2022-08-24 07:27 UTC, Takatatsu9 commented on Battleship.Test/EnemyshipTest.vb
> -
なるほど、最初からそう言ってくれれば良かったんですけど。
わかりやすい説明とは知る必要もないことすら事細かに全てを説明することではなく、
知りたいことをピンポイントに絞ってシンプルに説明することなんです。

2022-08-24 07:33 UTC, Takatatsu9 reviewed
Done

2022-08-24 07:33 UTC, Takatatsu9 commented on Battleship/QuestionForPlayer.vb
> +    ''' そうでない場合はFalse</returns>
[Q] この改行、IntelliSenseで繋がって表示されませんか？

これつい最近同じこと言ったばかりだな

2022-08-24 07:33 UTC, Takatatsu9 commented on Battleship/BattleshipGame.vb
> +    Public Sub CarryOutBattleshipGameProcess()
[Q] `CarryOut`ってどういう意味ですか？

2022-08-24 07:33 UTC, Takatatsu9 commented on Battleship.Test/CursorTest.vb
> +        <Test()> Public Sub 水平でのカーソル位置がテーブルの右端を超えると18に修正する()
[IMO] 18に修正するなんて言われても18が何を指すのか全くわかりません。
もし他の人が修正をしたとき、デザインが大きく変わって18以外になったとしても
絶対に18にならなくてはいけないというテストなのかとも受け取られてしまいます。

2022-08-24 07:46 UTC, konta3291 commented on Battleship/BattleshipGame.vb
> +    Public Sub CarryOutBattleshipGameProcess()
実行する、成し遂げる、遂行するの意味があります。

2022-08-24 07:46 UTC, konta3291 commented on Battleship/QuestionForPlayer.vb
> +    ''' そうでない場合はFalse</returns>
申し訳ありません。
繋がって表示されるためコメントを変更します。

2022-08-24 07:47 UTC, konta3291 commented on Battleship.Test/CursorTest.vb
> +        <Test()> Public Sub 水平でのカーソル位置がテーブルの右端を超えると18に修正する()
ご指摘ありがとうございます。
テストメソッド名を変更します。

2022-08-24 07:48 UTC, Takatatsu9 commented on Battleship/BattleshipGame.vb
> +    Public Sub CarryOutBattleshipGameProcess()
なるほど。アプリ開発やってて一度も使ったことない言葉ですね。
よく使ってるのは`Execute〜`です。exe拡張子の名前の由来かな

2022-08-24 08:02 UTC, konta3291 commented on Battleship/QuestionForPlayer.vb
> +    ''' そうでない場合はFalse</returns>
繋がって表示されるため、改行をなくしました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/361247055e6d956399d7417e95f3b1b015a13fd3
ご確認よろしくお願いします。

2022-08-24 08:02 UTC, konta3291 commented on Battleship.Test/CursorTest.vb
> +        <Test()> Public Sub 水平でのカーソル位置がテーブルの右端を超えると18に修正する()
テストメソッド名を変更しました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/13ff25476ddd664891db300fe118340e22d8d1ee

2022-08-24 23:22 UTC, konta3291 commented on Battleship/BattleshipGame.vb
> +    Public Sub CarryOutBattleshipGameProcess()
carry outよりExecuteの方が一般的でしたら、そちらに修正します。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/78335c6da6a4f4ccac72a0ded450f1db7c650d39
ご確認よろしくお願いします。

2022-08-24 23:23 UTC, konta3291 commented
メソッド名を変更するために強制Pushしました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/78335c6da6a4f4ccac72a0ded450f1db7c650d39

2022-08-25 00:10 UTC, nabemasamasa commented
……強制Push祭りですが、私はどこからレビューすればいいですか？ 46209b2 から？

2022-08-25 00:16 UTC, konta3291 commented
> ……強制Push祭りですが、私はどこからレビューすればいいですか？ [46209b2](https://github.com/konta3291/Battleship/commit/46209b2a0e16084d1b7e5b20d3631497cd063084) から？

申し訳ありません。
そちらのコミットからお願いいたします。

2022-08-25 00:53 UTC, nabemasamasa requested changes, later dismissed
done

2022-08-25 00:53 UTC, nabemasamasa commented on Battleship/Cursor.vb
> +    Public Function CorrectionOfLeftAndRightPositionThatWentOffGameTable(cursorLeft As Integer) As Integer
Collectionが動詞である根拠を示してほしい

2022-08-25 01:06 UTC, konta3291 commented on Battleship/Cursor.vb
> +    Public Function CorrectionOfLeftAndRightPositionThatWentOffGameTable(cursorLeft As Integer) As Integer
申し訳ありません。
Correctionは名詞だったため、動詞のCorrectに修正します。

2022-08-25 01:13 UTC, konta3291 commented on Battleship/Cursor.vb
> +    Public Function CorrectionOfLeftAndRightPositionThatWentOffGameTable(cursorLeft As Integer) As Integer
名前を修正しました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/a87519b2692e8253e45f77167fd76243171e8db2
ご確認よろしくお願いします。

2022-08-25 01:15 UTC, konta3291 commented
メソッド名がコーディングルール違反をしていたため修正し強制Pushしました。
コミットはこちらです：https://github.com/konta3291/Battleship/pull/5/commits/a87519b2692e8253e45f77167fd76243171e8db2

2022-08-25 02:31 UTC, nabemasamasa commented
もしかして「コミットはこちらです a87519b2692e8253e45f77167fd76243171e8db2 」ってそのコミットの差分を全部レビューしないといけないってことですか？？？
一応確認ですが、私はForcepush前の差分を全部レビューしてるはずで、 [force-pushed](https://github.com/konta3291/Battleship/compare/d16b8f86ce16ec6e7cfc29de30f9f5ebbee6e0e7..6252b826334120404dd060f319708d2121e7e4aa) のリンクで見れる差分が前回レビュー時との差分のはずと判断できそうだから、それをレビューすれば良い、でいいんですよね？


今までは時間に余裕があったので(手間ですが)全部レビューしなおしたり精査してどれをレビューすべき差分か確認してきたけど、ちょっと今スケジュールがタイトなので毎回Forcepushされる度にそこまでしたくないです……。


↓こんな感じで、次回からはForcePushした時にレビュアーが次どこからレビューしないといけないのかコメントお願いします。目的は、可能な限りレビュアーの負担を減らすことです。目的に合致すれば別のやり方を提案してもいいです。
![image](https://user-images.githubusercontent.com/20126608/186559250-8c5670be-f1a1-4135-bad9-2f9774cd4e95.png)

2022-08-25 02:53 UTC, konta3291 commented
レビュアーへの配慮が足りていなく申し訳ありません。
@nabemasamasaさんがおっしゃるとおり、force-pushedの差分のみレビューをお願いいたします。
今後からは、レビュアーへの配慮を考えforcePush後にどのコミットをレビューしていただきたいかコメントを書くようにします。
お忙しいところお手数をおかけしてしまい申し訳ありませんでした。

2022-08-25 04:24 UTC, nabemasamasa reviewed
Done!

2022-08-25 04:48 UTC, danielkaneko reviewed
Done ( 332592f まで)

2022-08-25 05:10 UTC, nabemasamasa reviewed
Done テスト充実 👍

2022-08-25 05:50 UTC, Takatatsu9 commented
ちなみにですね、fixupコミットをrebase -iせずにpushしてレビューしてもらって、
全部OK貰ったらrebase -iしてforce-pushするって手があるんですよ。
そうすると差分が見やすいし、どこからレビューしてないか聞かなくてもわかる。

2022-08-25 05:53 UTC, Takatatsu9 reviewed
Done

2022-08-25 05:56 UTC, Takatatsu9 commented on Battleship/BattleshipGame.vb
> +    Public Sub PlayBattleshipGame()
どうでもいいけどMacやiOSで打った波括弧（`〜`）がWindows環境だと
めっちゃ汚く表示されるのMicrosoftの嫌がらせを感じる

2022-08-25 07:15 UTC, konta3291 commented
> ちなみにですね、fixupコミットをrebase -iせずにpushしてレビューしてもらって、 全部OK貰ったらrebase -iしてforce-pushするって手があるんですよ。 そうすると差分が見やすいし、どこからレビューしてないか聞かなくてもわかる。

ありがとうございます。今後からはfixupコミットをレビューしていただいてからすべてが完了後rebase -iしforcePushします。
レビュアーへの配慮が足りていなく申し訳ありませんでした。

2022-08-26 01:43 UTC, konta3291 commented
コミットを整理し強制Pushしました。
お時間があるときにレビューお願いいたします。

2022-08-26 01:48 UTC, Takatatsu9 commented
[Q] コミット整理しただけなのにどうして[変化点](https://github.com/konta3291/Battleship/compare/ada1bc6ee1f8774e179d6d8e53899ca780c7eb90..fcfbefe33d55aadac9212b95b8c95835009f85e7)があるんですか？
変化点がある部分以外はレビュー済みなのでレビューする必要ないんですが、対象コミットは教えてくれないのですか？
それともレビュー済みのところもレビューしてということですか？

2022-08-26 02:05 UTC, konta3291 commented
[変更点](https://github.com/konta3291/Battleship/compare/ada1bc6ee1f8774e179d6d8e53899ca780c7eb90..fcfbefe33d55aadac9212b95b8c95835009f85e7) を確認しましたが、レビューをしていただく必要はないと思います。
Class1を使わないまま残していたので、コミット整理とともにClass1の名前を変更し使うことにしました。
コードの内容自体は変わっていないためレビューしていただかなくとも大丈夫です。

また、ValueNeedToMakeEnemyship.vbの方もコード自体に変更はないためレビューしていただかなくとも大丈夫です。

わかりづらいPushをしてしまい申し訳ありませんでした。

2022-08-26 02:07 UTC, Takatatsu9 commented
コードが変わって無くてもファイル構成が変わってるのでレビューする必要はあります。
ファイル無くなっても参照残ってるとか、参照無くなってもファイル残ってるとかあるんでね。

2022-08-26 02:13 UTC, konta3291 commented
些細な事だと考えてしまっていました。
お手数をおかけするようなことをしてしまい申し訳ありません。
お手すきの際で大丈夫なので、申し訳ないのですがレビューをお願いいたします。

2022-08-26 02:21 UTC, Takatatsu9 commented
[Q] レビューすべき、変化点が含まれてるコミットはどれですか？
それともレビュー済みのところもレビューしてということですか？

2022-08-26 02:26 UTC, konta3291 commented
Class1を変更したのはこちらのコミットです。https://github.com/konta3291/Battleship/pull/5/commits/c0e3f2dc4043f8d5cb48b0903afabe2668874a8a

2022-08-26 04:18 UTC, Takatatsu9 reviewed
Done

2022-08-26 04:53 UTC, danielkaneko reviewed
Done ( c0e3f2d まで)

2022-08-26 07:33 UTC, konta3291 commented
@nabemasamasa 
コミットは整理する際に、今まで使わないでいたClass1をEnemyshipTestクラスに変更してしまいました。
変更をしてしまったためコミットのレビューをお願いいたします。
変更があったコミットはこちらです。https://github.com/konta3291/Battleship/pull/5/commits/c0e3f2dc4043f8d5cb48b0903afabe2668874a8a

余計な行動でレビューするものを増やしてしまい申し訳ありませんでした。

2022-08-28 23:12 UTC, nabemasamasa reviewed
Done

2022-08-28 23:13 UTC, nabemasamasa reviewed
Done (レビュー時コメントとしてコメントされてなくて見づらかったので再度)

2022-08-28 23:13 UTC, nabemasamasa commented on Battleship.Test/Battleship.Test.vbproj
> -    <Compile Include="Class1.vb" />
[nits] 次回コミット整理する機会があれば、これはコミット分けてあげたいですね。
「敵船を作る処理追加」とは別件の修正なので。

2022-08-28 23:20 UTC, konta3291 commented on Battleship.Test/Battleship.Test.vbproj
> -    <Compile Include="Class1.vb" />
ご指摘ありがとうございます。
かしこまりました、今後ファイルを削除する際はコミットを分けるようにします。

2022-08-29 00:07 UTC, merged

2022-08-29 04:52 UTC, danielkaneko reviewed
Done ( 212e938 )まで

2022-08-31 04:45 UTC, danielkaneko reviewed
Done ( ed39891 )まで

2022-09-01 04:41 UTC, danielkaneko reviewed
Done ( 40f4854 )まで

2022-09-02 04:55 UTC, danielkaneko reviewed
Done( 04bc1a7 )まで

2022-09-05 04:49 UTC, danielkaneko reviewed
Done( fcfbefe )まで